"""Procedural 3D geometry, written as PLY."""

from __future__ import annotations

import math

Vec3 = tuple[float, float, float]
Face = tuple[int, int, int]

# Arch dimensions in millimetres.
HALF_WIDTH_MM = 27.0  # ~54 mm across the molars
ARCH_DEPTH_MM = 38.0
ANTERIOR_TEETH = 14  # per arch: 2 incisors, 1 canine, 2 premolars, 3 molars per side


def _lerp(a: float, b: float, t: float) -> float:
    return a + (b - a) * t


def _stitch(rings: list[list[Vec3]], cap_bottom: bool, cap_top: bool) -> tuple[list[Vec3], list[Face]]:
    """Stitch equal-length rings into a triangle mesh, optionally capping the ends."""
    verts: list[Vec3] = [v for ring in rings for v in ring]
    n = len(rings[0])
    faces: list[Face] = []

    for r in range(len(rings) - 1):
        a = r * n
        b = (r + 1) * n
        for i in range(n):
            j = (i + 1) % n
            # Two triangles per quad. Winding chosen so normals face outward for
            # rings ordered counter-clockwise seen from +Y.
            faces.append((a + i, a + j, b + j))
            faces.append((a + i, b + j, b + i))

    if cap_bottom:
        centre = len(verts)
        verts.append(_centroid(rings[0]))
        for i in range(n):
            j = (i + 1) % n
            faces.append((centre, j, i))

    if cap_top:
        last = (len(rings) - 1) * n
        centre = len(verts)
        verts.append(_centroid(rings[-1]))
        for i in range(n):
            j = (i + 1) % n
            faces.append((centre, last + i, last + j))

    return verts, faces


def _centroid(ring: list[Vec3]) -> Vec3:
    n = len(ring)
    return (
        sum(p[0] for p in ring) / n,
        sum(p[1] for p in ring) / n,
        sum(p[2] for p in ring) / n,
    )


def _arch_point(t: float) -> tuple[float, float]:
    """Map t in [-1, 1] onto the arch curve. Anterior at t=0, molars at |t|=1."""
    x = t * HALF_WIDTH_MM
    z = -ARCH_DEPTH_MM * (t * t)
    return x, z


def _tooth(
    cx: float, cz: float, y_base: float, rx: float, rz: float, height: float,
    segments: int = 20, rings: int = 6,
) -> tuple[list[Vec3], list[Face]]:
    """A tapered elliptical prism: one tooth-shaped stand-in."""
    built: list[list[Vec3]] = []
    for r in range(rings):
        u = r / (rings - 1)
        # Slight occlusal taper, plus a small waist so adjacent teeth read as separate.
        taper = 1.0 - 0.18 * u - 0.05 * math.sin(math.pi * u)
        y = y_base + height * u
        ring: list[Vec3] = []
        for i in range(segments):
            a = 2.0 * math.pi * i / segments
            ring.append((cx + rx * taper * math.cos(a), y, cz + rz * taper * math.sin(a)))
        built.append(ring)
    return _stitch(built, cap_bottom=True, cap_top=True)


def _gum(arch: list[tuple[float, float]], half_width: float = 3.0, half_height: float = 3.2) -> tuple[list[Vec3], list[Face]]:
    """A rounded ridge running along the arch, sitting below the gum line."""
    built: list[list[Vec3]] = []
    segments = 10
    for i, (x, z) in enumerate(arch):
        # Local horizontal normal, from the tangent.
        px, pz = arch[max(i - 1, 0)]
        nx_, nz_ = arch[min(i + 1, len(arch) - 1)]
        tx, tz = nx_ - px, nz_ - pz
        length = math.hypot(tx, tz) or 1.0
        normal = (-tz / length, tx / length)

        ring: list[Vec3] = []
        for k in range(segments):
            a = 2.0 * math.pi * k / segments
            off = half_width * math.cos(a)
            y = -half_height + half_height * math.sin(a)
            ring.append((x + normal[0] * off, y, z + normal[1] * off))
        built.append(ring)
    return _stitch(built, cap_bottom=False, cap_top=False)


def build_dental_arch(teeth: int = ANTERIOR_TEETH) -> tuple[list[Vec3], list[Face]]:
    """Both rows: one arch of teeth sitting on a gingival ridge."""
    verts: list[Vec3] = []
    faces: list[Face] = []

    ts = [(-1.0 + 2.0 * i / (teeth - 1)) for i in range(teeth)]
    for t in ts:
        cx, cz = _arch_point(t)
        s = abs(t)
        rx = _lerp(2.4, 4.7, s)
        rz = _lerp(2.7, 4.5, s)
        height = _lerp(8.6, 6.8, s)
        v, f = _tooth(cx, cz, 0.0, rx, rz, height)
        base = len(verts)
        verts.extend(v)
        faces.extend((a + base, b + base, c + base) for a, b, c in f)

    dense = [_arch_point(-1.0 + 2.0 * i / 48) for i in range(49)]
    v, f = _gum(dense)
    base = len(verts)
    verts.extend(v)
    faces.extend((a + base, b + base, c + base) for a, b, c in f)

    return verts, faces


def to_ply(verts: list[Vec3], faces: list[Face]) -> bytes:
    lines = [
        "ply",
        "format ascii 1.0",
        "comment procedural stand-in generated by bone_viewer_api.pipeline.meshgen",
        "comment NOT a reconstruction and NOT anatomy - fixture geometry only",
        f"element vertex {len(verts)}",
        "property float x",
        "property float y",
        "property float z",
        f"element face {len(faces)}",
        "property list uchar int vertex_indices",
        "end_header",
    ]
    lines.extend(f"{x:.4f} {y:.4f} {z:.4f}" for x, y, z in verts)
    lines.extend(f"3 {a} {b} {c}" for a, b, c in faces)
    return ("\n".join(lines) + "\n").encode("ascii")
