"""Demo datasets, generated from the catalogue they are listed in.

Each entry below was read from the JSON-LD metadata that
https://saga-it.com/dicom/samples publishes for its tiles -- name, description,
licence, anatomy, source collection, DOI and the exact size of the series zip.
Transcribing 28 records by hand is how a licence ends up attributed to the wrong
study, so they are extracted instead.

**Do not edit by hand.** Re-run tools/refresh_sample_catalogue.py against that
page to update them; it rewrites this file. `app/samples.py` holds the logic and
the reasoning about licensing, and is the file to read first.

Every study here is CC BY 3.0 or 4.0, which permits commercial use **with
attribution**. That is why `collection`, `source` and `doi` travel with each
entry: showing the licence without the attribution does not satisfy it.
"""

from __future__ import annotations

#: Where the series zips are hosted. Named so a deployment can mirror them.
SAGA_BASE = "https://saga-it.com/dicom/samples/files"

ENTRIES: list[dict] = [
    {
        'id': 'ct-abdomen-c4kc-kits',
        'title': 'Abdominal CT: C4KC-KiTS Kidney Study',
        'description': 'Contrast-enhanced (arterial-phase) abdominal CT from the KiTS kidney tumor cohort, a renal-focused volume of roughly 100 axial slices. Demonstrates contrast-phase viewing, MPR, and soft-tissue windowing.',
        'url': 'https://saga-it.com/dicom/samples/files/ct-abdomen-c4kc-kits/series.zip',
        'licence': 'CC BY 3.0',
        'bytes': 30578606,
        'modality': 'CT',
        'anatomy': 'Abdomen / Kidneys',
        'collection': 'C4KC-KiTS (Kidney Tumor Segmentation Challenge)',
        'source': 'https://www.cancerimagingarchive.net/collection/c4kc-kits/',
        'doi': 'https://doi.org/10.7937/TCIA.2019.IX49E8NX',
    },
    {
        'id': 'ct-chest-lidc-idri',
        'title': 'Chest CT: LIDC-IDRI Lung Nodule Study',
        'description': 'Diagnostic chest CT from the LIDC-IDRI reference database, a thin-slice volume of roughly 250 axial images used widely for lung-nodule detection research. Demonstrates volumetric scrolling, MPR, and lung/mediastinum window presets.',
        'url': 'https://saga-it.com/dicom/samples/files/ct-chest-lidc-idri/series.zip',
        'licence': 'CC BY 3.0',
        'bytes': 71546064,
        'modality': 'CT',
        'anatomy': 'Chest / Lungs',
        'collection': 'LIDC-IDRI (Lung Image Database Consortium)',
        'source': 'https://www.cancerimagingarchive.net/collection/lidc-idri/',
        'doi': 'https://doi.org/10.7937/K9/TCIA.2015.LO9QL9SX',
    },
    {
        'id': 'ct-lung-screening-nlst',
        'title': 'Chest CT: NLST Lung Cancer Screening',
        'description': 'Single-volume thin-slice chest CT from the NLST low-dose lung screening cohort, roughly 150 axial slices. Demonstrates volumetric viewing, multiplanar reconstruction (MPR), and window/level presets.',
        'url': 'https://saga-it.com/dicom/samples/files/ct-lung-screening-nlst/series.zip',
        'licence': 'CC BY 4.0',
        'bytes': 46802035,
        'modality': 'CT',
        'anatomy': 'Chest / Lungs',
        'collection': 'NLST (National Lung Screening Trial)',
        'source': 'https://www.cancerimagingarchive.net/collection/nlst/',
        'doi': 'https://doi.org/10.7937/TCIA.HMQ8-J677',
    },
    {
        'id': 'ct-pancreas-pancreas-ct',
        'title': 'Pancreatic CT: Pancreas-CT Reference Study',
        'description': 'Contrast-enhanced abdominal CT centered on the pancreas, a thin-slice volume of roughly 200 axial images from the NIH reference set. Demonstrates high-resolution volumetric viewing, MPR, and soft-tissue windowing of upper-abdominal anatomy.',
        'url': 'https://saga-it.com/dicom/samples/files/ct-pancreas-pancreas-ct/series.zip',
        'licence': 'CC BY 3.0',
        'bytes': 52341015,
        'modality': 'CT',
        'anatomy': 'Abdomen / Pancreas',
        'collection': 'Pancreas-CT',
        'source': 'https://www.cancerimagingarchive.net/collection/pancreas-ct/',
        'doi': 'https://doi.org/10.7937/K9/TCIA.2016.tNB1kqBU',
    },
    {
        'id': 'dx-chest-covid-19-ar',
        'title': 'Chest X-ray: Rural COVID-19 Population Study',
        'description': 'Portable AP chest radiograph (digital X-ray) from a rural COVID-19 positive population. Demonstrates digital radiography viewing with presentation-state rendering.',
        'url': 'https://saga-it.com/dicom/samples/files/dx-chest-covid-19-ar/series.zip',
        'licence': 'CC BY 4.0',
        'bytes': 9070362,
        'modality': 'DX',
        'anatomy': 'Chest',
        'collection': 'COVID-19-AR (Chest Imaging of a Rural COVID-19 Population)',
        'source': 'https://www.cancerimagingarchive.net/collection/covid-19-ar/',
        'doi': 'https://doi.org/10.7937/tcia.2020.py71-5978',
    },
    {
        'id': 'dx-chest-covid-19-ny-sbu',
        'title': 'Chest X-ray: Stony Brook COVID-19 Study',
        'description': 'AP chest radiograph (computed radiography) from the Stony Brook COVID-19 positive-case cohort. Demonstrates single-image 2D X-ray viewing, zoom, pan, and window/level.',
        'url': 'https://saga-it.com/dicom/samples/files/dx-chest-covid-19-ny-sbu/series.zip',
        'licence': 'CC BY 4.0',
        'bytes': 9614803,
        'modality': 'DX',
        'anatomy': 'Chest',
        'collection': 'Stony Brook University COVID-19 Positive Cases (COVID-19-NY-SBU)',
        'source': 'https://www.cancerimagingarchive.net/collection/covid-19-ny-sbu/',
        'doi': 'https://doi.org/10.7937/TCIA.BBAG-2923',
    },
    {
        'id': 'dx-chest-lidc-idri',
        'title': 'Chest X-ray: LIDC-IDRI PA & Lateral Study',
        'description': 'PA and lateral chest radiographs (digital X-ray) from the LIDC-IDRI reference database. Demonstrates two-view 2D X-ray comparison and presentation-state rendering.',
        'url': 'https://saga-it.com/dicom/samples/files/dx-chest-lidc-idri/series.zip',
        'licence': 'CC BY 3.0',
        'bytes': 8602248,
        'modality': 'DX',
        'anatomy': 'Chest',
        'collection': 'LIDC-IDRI (Lung Image Database Consortium)',
        'source': 'https://www.cancerimagingarchive.net/collection/lidc-idri/',
        'doi': 'https://doi.org/10.7937/K9/TCIA.2015.LO9QL9SX',
    },
    {
        'id': 'dx-chest-varepop-apollo',
        'title': 'Chest X-ray: VAREPOP-APOLLO Oncology Study',
        'description': 'Single-view AP chest radiograph from the VA precision-oncology APOLLO research network. Demonstrates single-image 2D X-ray viewing and grayscale window/level adjustment.',
        'url': 'https://saga-it.com/dicom/samples/files/dx-chest-varepop-apollo/series.zip',
        'licence': 'CC BY 4.0',
        'bytes': 10421498,
        'modality': 'DX',
        'anatomy': 'Chest',
        'collection': 'VA Research Precision Oncology Program — APOLLO (VAREPOP-APOLLO)',
        'source': 'https://www.cancerimagingarchive.net/collection/varepop-apollo/',
        'doi': 'https://doi.org/10.7937/ghkn-md15',
    },
    {
        'id': 'mg-mammography-cbis-ddsm',
        'title': 'Mammography: CBIS-DDSM Mass Test Set',
        'description': 'Standardized digital mammography (CC view) from the CBIS-DDSM benchmark set. Demonstrates 2D high-resolution viewing, zoom, and pan.',
        'url': 'https://saga-it.com/dicom/samples/files/mg-mammography-cbis-ddsm/series.zip',
        'licence': 'CC BY 3.0',
        'bytes': 236949,
        'modality': 'MG',
        'anatomy': 'Breast',
        'collection': 'CBIS-DDSM (Curated Breast Imaging Subset of DDSM)',
        'source': 'https://www.cancerimagingarchive.net/collection/cbis-ddsm/',
        'doi': 'https://doi.org/10.7937/K9/TCIA.2016.7O02S9CY',
    },
    {
        'id': 'mg-mammography-cmmd',
        'title': 'Mammography: CMMD Chinese Mammography Database',
        'description': 'Full-field digital mammography from the CMMD biopsy-confirmed database, with standard CC and MLO projections. Demonstrates multi-view 2D mammography viewing and high-resolution zoom.',
        'url': 'https://saga-it.com/dicom/samples/files/mg-mammography-cmmd/series.zip',
        'licence': 'CC BY 4.0',
        'bytes': 4056354,
        'modality': 'MG',
        'anatomy': 'Breast',
        'collection': 'CMMD (Chinese Mammography Database)',
        'source': 'https://www.cancerimagingarchive.net/collection/cmmd/',
        'doi': 'https://doi.org/10.7937/tcia.eqde-4b16',
    },
    {
        'id': 'mg-mammography-ea1141',
        'title': 'Mammography: EA1141 Dense-Breast Screening',
        'description': "Bilateral screening mammography from the EA1141 dense-breast trial. Demonstrates standard digital mammography viewing alongside the trial's tomosynthesis context.",
        'url': 'https://saga-it.com/dicom/samples/files/mg-mammography-ea1141/series.zip',
        'licence': 'CC BY 4.0',
        'bytes': 27109994,
        'modality': 'MG',
        'anatomy': 'Breast',
        'collection': 'EA1141 (Abbreviated Breast MRI and Digital Tomosynthesis Mammography)',
        'source': 'https://www.cancerimagingarchive.net/collection/ea1141/',
        'doi': 'https://doi.org/10.7937/2bas-hr33',
    },
    {
        'id': 'mg-tomosynthesis-victre',
        'title': 'Mammography: VICTRE In-Silico Tomosynthesis',
        'description': 'Simulated digital breast tomosynthesis projection set from the VICTRE in-silico clinical trial. Demonstrates tomosynthesis projection scrolling and synthetic mammography rendering.',
        'url': 'https://saga-it.com/dicom/samples/files/mg-tomosynthesis-victre/series.zip',
        'licence': 'CC BY 3.0',
        'bytes': 152853749,
        'modality': 'MG',
        'anatomy': 'Breast',
        'collection': 'VICTRE (Virtual Imaging Clinical Trial for Regulatory Evaluation)',
        'source': 'https://www.cancerimagingarchive.net/collection/victre/',
        'doi': 'https://doi.org/10.7937/TCIA.2019.ho23nxaw',
    },
    {
        'id': 'mr-brain-upenn-gbm',
        'title': 'Brain MRI: UPENN-GBM Glioblastoma Study',
        'description': 'Multi-parametric brain tumor MRI from the UPENN-GBM glioblastoma cohort, an axial T2 series used for tumor characterization. Demonstrates neuro MR viewing, MPR, and segmentation context.',
        'url': 'https://saga-it.com/dicom/samples/files/mr-brain-upenn-gbm/series.zip',
        'licence': 'CC BY 4.0',
        'bytes': 2798097,
        'modality': 'MR',
        'anatomy': 'Brain',
        'collection': 'UPENN-GBM (Glioblastoma at the University of Pennsylvania)',
        'source': 'https://www.cancerimagingarchive.net/collection/upenn-gbm/',
        'doi': 'https://doi.org/10.7937/TCIA.709X-DN49',
    },
    {
        'id': 'mr-breast-ispy1',
        'title': 'Breast MRI: I-SPY 1 Trial',
        'description': 'Sagittal breast MRI series from the I-SPY 1 / ACRIN 6657 breast cancer trial. Demonstrates volumetric MR scrolling, multiplanar reconstruction (MPR), and soft-tissue window/level review.',
        'url': 'https://saga-it.com/dicom/samples/files/mr-breast-ispy1/series.zip',
        'licence': 'CC BY 3.0',
        'bytes': 1090679,
        'modality': 'MR',
        'anatomy': 'Breast',
        'collection': 'ISPY1',
        'source': 'https://www.cancerimagingarchive.net/collection/ispy1/',
        'doi': 'https://doi.org/10.7937/K9/TCIA.2016.HdHpgJLK',
    },
    {
        'id': 'mr-head-vestibular-schwannoma',
        'title': 'Head MRI: Vestibular Schwannoma Routine MRI',
        'description': 'Routine clinical brain MRI from a multi-center vestibular schwannoma dataset, a contrast T1 series acquired for treatment planning. Demonstrates thin-slice neuro MR viewing and MPR.',
        'url': 'https://saga-it.com/dicom/samples/files/mr-head-vestibular-schwannoma/series.zip',
        'licence': 'CC BY 4.0',
        'bytes': 4371179,
        'modality': 'MR',
        'anatomy': 'Head / Brain',
        'collection': 'Vestibular-Schwannoma-MC-RC',
        'source': 'https://www.cancerimagingarchive.net/collection/vestibular-schwannoma-mc-rc/',
        'doi': 'https://doi.org/10.7937/HRZH-2N82',
    },
    {
        'id': 'mr-prostate-prostatex',
        'title': 'Prostate MRI: SPIE-AAPM PROSTATEx Challenge',
        'description': 'Diffusion-weighted (DWI) prostate MR series from the multi-parametric SPIE-AAPM PROSTATEx challenge. Demonstrates functional/diffusion MR viewing, MPR, and window/level review.',
        'url': 'https://saga-it.com/dicom/samples/files/mr-prostate-prostatex/series.zip',
        'licence': 'CC BY 3.0',
        'bytes': 623351,
        'modality': 'MR',
        'anatomy': 'Prostate',
        'collection': 'SPIE-AAPM PROSTATEx',
        'source': 'https://www.cancerimagingarchive.net/collection/prostatex/',
        'doi': 'https://doi.org/10.7937/K9TCIA.2017.MURS5CL',
    },
    {
        'id': 'nm-bone-cmb-pca',
        'title': 'Bone Scintigraphy: CMB-PCA Nuclear Medicine',
        'description': 'Planar bone scintigraphy (static views) from the Cancer Moonshot Biobank prostate cancer cohort. Demonstrates planar nuclear-medicine viewing and intensity-window adjustment.',
        'url': 'https://saga-it.com/dicom/samples/files/nm-bone-cmb-pca/series.zip',
        'licence': 'CC BY 4.0',
        'bytes': 309466,
        'modality': 'NM',
        'anatomy': 'Whole Body / Skeleton',
        'collection': 'Cancer Moonshot Biobank — Prostate Cancer Collection (CMB-PCA)',
        'source': 'https://www.cancerimagingarchive.net/collection/cmb-pca/',
        'doi': 'https://doi.org/10.7937/25t7-6y12',
    },
    {
        'id': 'nm-cardiac-varepop-apollo',
        'title': 'Myocardial Perfusion: VAREPOP-APOLLO SPECT',
        'description': 'Gated myocardial perfusion SPECT reconstruction from the VA precision-oncology APOLLO cohort. Demonstrates cardiac nuclear-medicine image review and intensity windowing.',
        'url': 'https://saga-it.com/dicom/samples/files/nm-cardiac-varepop-apollo/series.zip',
        'licence': 'CC BY 4.0',
        'bytes': 148250,
        'modality': 'NM',
        'anatomy': 'Heart',
        'collection': 'VA Research Precision Oncology Program — APOLLO (VAREPOP-APOLLO)',
        'source': 'https://www.cancerimagingarchive.net/collection/varepop-apollo/',
        'doi': 'https://doi.org/10.7937/ghkn-md15',
    },
    {
        'id': 'nm-lung-acrin-nsclc',
        'title': 'Lung Nuclear Medicine: ACRIN 6668 Thorax Scan',
        'description': 'Planar lung nuclear-medicine imaging from the ACRIN 6668 non-small cell lung cancer trial. Demonstrates planar NM viewing within a multi-modality PET/CT workup.',
        'url': 'https://saga-it.com/dicom/samples/files/nm-lung-acrin-nsclc/series.zip',
        'licence': 'CC BY 3.0',
        'bytes': 1215223,
        'modality': 'NM',
        'anatomy': 'Chest / Lungs',
        'collection': 'ACRIN-NSCLC-FDG-PET (ACRIN 6668 Trial)',
        'source': 'https://www.cancerimagingarchive.net/collection/acrin-nsclc-fdg-pet/',
        'doi': 'https://doi.org/10.7937/tcia.2019.30ilqfcl',
    },
    {
        'id': 'nm-perfusion-cmb-lca',
        'title': 'Lung Perfusion Scan: CMB-LCA Nuclear Medicine',
        'description': 'Planar lung perfusion scintigraphy (anterior/posterior views) from the Cancer Moonshot Biobank lung cancer cohort. Demonstrates multi-frame planar nuclear-medicine image review.',
        'url': 'https://saga-it.com/dicom/samples/files/nm-perfusion-cmb-lca/series.zip',
        'licence': 'CC BY 4.0',
        'bytes': 58953,
        'modality': 'NM',
        'anatomy': 'Chest / Lungs',
        'collection': 'Cancer Moonshot Biobank — Lung Cancer Collection (CMB-LCA)',
        'source': 'https://www.cancerimagingarchive.net/collection/cmb-lca/',
        'doi': 'https://doi.org/10.7937/3cx3-s132',
    },
    {
        'id': 'pt-bone-naf-prostate',
        'title': 'Bone PET: NaF PROSTATE Total-Body Scan',
        'description': 'F-18 NaF total-body bone PET from a prostate cancer cohort, used to assess skeletal metastases. Demonstrates whole-body PET scrolling and SUV-based bone-uptake review.',
        'url': 'https://saga-it.com/dicom/samples/files/pt-bone-naf-prostate/series.zip',
        'licence': 'CC BY 3.0',
        'bytes': 2289507,
        'modality': 'PT',
        'anatomy': 'Whole Body / Skeleton',
        'collection': 'NaF PROSTATE',
        'source': 'https://www.cancerimagingarchive.net/collection/naf-prostate/',
        'doi': 'https://doi.org/10.7937/K9/TCIA.2015.ISOQTHKO',
    },
    {
        'id': 'pt-breast-qin-01',
        'title': 'Breast PET: QIN-Breast Quantitative Imaging',
        'description': 'Attenuation-corrected FDG-PET volume from the Quantitative Imaging Network breast cohort. Demonstrates volumetric PET scrolling, SUV-based uptake review, and grayscale/inverted PET presentation.',
        'url': 'https://saga-it.com/dicom/samples/files/pt-breast-qin-01/series.zip',
        'licence': 'CC BY 3.0',
        'bytes': 1361991,
        'modality': 'PT',
        'anatomy': 'Breast / Whole Body',
        'collection': 'QIN-Breast',
        'source': 'https://www.cancerimagingarchive.net/collection/qin-breast/',
        'doi': 'https://doi.org/10.7937/K9/TCIA.2016.21JUEBH0',
    },
    {
        'id': 'pt-chest-rider-lung-pet-ct',
        'title': 'Chest PET: RIDER Lung PET-CT Test-Retest',
        'description': 'Reconstructed chest FDG-PET from the RIDER test-retest reproducibility cohort. Demonstrates PET volumetric viewing and SUV review for quantitative imaging workflows.',
        'url': 'https://saga-it.com/dicom/samples/files/pt-chest-rider-lung-pet-ct/series.zip',
        'licence': 'CC BY 3.0',
        'bytes': 4184994,
        'modality': 'PT',
        'anatomy': 'Chest / Torso',
        'collection': 'RIDER Lung PET-CT',
        'source': 'https://www.cancerimagingarchive.net/collection/rider-lung-pet-ct/',
        'doi': 'https://doi.org/10.7937/k9/tcia.2015.ofip7tvm',
    },
    {
        'id': 'pt-whole-body-acrin-nsclc',
        'title': 'Whole-Body PET: ACRIN 6668 NSCLC FDG-PET',
        'description': 'Whole-body FDG-PET from the ACRIN 6668 non-small cell lung cancer trial. Demonstrates volumetric PET scrolling, SUV viewing, and inverted-grayscale presentation.',
        'url': 'https://saga-it.com/dicom/samples/files/pt-whole-body-acrin-nsclc/series.zip',
        'licence': 'CC BY 3.0',
        'bytes': 4885321,
        'modality': 'PT',
        'anatomy': 'Whole Body / Lung',
        'collection': 'ACRIN-NSCLC-FDG-PET (ACRIN 6668 Trial)',
        'source': 'https://www.cancerimagingarchive.net/collection/acrin-nsclc-fdg-pet/',
        'doi': 'https://doi.org/10.7937/tcia.2019.30ilqfcl',
    },
    {
        'id': 'us-kidney-cmb-crc',
        'title': 'Renal Ultrasound: CMB-CRC Kidney Study',
        'description': 'Complete renal ultrasound exam from the Cancer Moonshot Biobank colorectal cancer cohort. Demonstrates multi-frame ultrasound review and grayscale abdominal imaging.',
        'url': 'https://saga-it.com/dicom/samples/files/us-kidney-cmb-crc/series.zip',
        'licence': 'CC BY 4.0',
        'bytes': 10886604,
        'modality': 'US',
        'anatomy': 'Abdomen / Kidneys',
        'collection': 'Cancer Moonshot Biobank — Colorectal Cancer Collection (CMB-CRC)',
        'source': 'https://www.cancerimagingarchive.net/collection/cmb-crc/',
        'doi': 'https://doi.org/10.7937/djg7-gz87',
    },
    {
        'id': 'us-liver-b-mode-ceus',
        'title': 'Liver Ultrasound: B-mode Liver Mass Study',
        'description': 'B-mode abdominal ultrasound of a liver mass from a contrast-enhanced ultrasound study set. Demonstrates ultrasound cine playback and grayscale image rendering.',
        'url': 'https://saga-it.com/dicom/samples/files/us-liver-b-mode-ceus/series.zip',
        'licence': 'CC BY 4.0',
        'bytes': 63659580,
        'modality': 'US',
        'anatomy': 'Abdomen / Liver',
        'collection': 'Ultrasound data of a variety of liver masses (B-mode-and-CEUS-Liver)',
        'source': 'https://www.cancerimagingarchive.net/collection/b-mode-and-ceus-liver/',
        'doi': 'https://doi.org/10.7937/TCIA.2021.v4z7-tc39',
    },
    {
        'id': 'us-lymph-node-cmb-lca',
        'title': 'Lymph Node Ultrasound: CMB-LCA Biopsy Guidance',
        'description': 'Ultrasound from a guided superficial lymph-node biopsy in the Cancer Moonshot Biobank lung cancer cohort. Demonstrates interventional ultrasound cine review and image-guided procedure context.',
        'url': 'https://saga-it.com/dicom/samples/files/us-lymph-node-cmb-lca/series.zip',
        'licence': 'CC BY 4.0',
        'bytes': 4333623,
        'modality': 'US',
        'anatomy': 'Neck / Lymph Node',
        'collection': 'Cancer Moonshot Biobank — Lung Cancer Collection (CMB-LCA)',
        'source': 'https://www.cancerimagingarchive.net/collection/cmb-lca/',
        'doi': 'https://doi.org/10.7937/3cx3-s132',
    },
    {
        'id': 'us-prostate-mri-biopsy',
        'title': 'Prostate Ultrasound: MRI-Targeted Biopsy',
        'description': 'Trans-rectal ultrasound from a multi-modal MR/US fusion biopsy cohort. Demonstrates ultrasound rendering and the multi-modality workflow of correlating MR + US imaging.',
        'url': 'https://saga-it.com/dicom/samples/files/us-prostate-mri-biopsy/series.zip',
        'licence': 'CC BY 4.0',
        'bytes': 15365767,
        'modality': 'US',
        'anatomy': 'Prostate',
        'collection': 'Prostate-MRI-US-Biopsy',
        'source': 'https://www.cancerimagingarchive.net/collection/prostate-mri-us-biopsy/',
        'doi': 'https://doi.org/10.7937/TCIA.2020.A61IOC1A',
    },
]
